spring.application.name=SpringAIWorkshop

# set open API key
spring.ai.openai.api-key=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
